"""Descrição da migração

Revision ID: a6231ed3a210
Revises: 
Create Date: 2023-11-11 12:13:39.645212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6231ed3a210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cambio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carros', schema=None) as batch_op:
        batch_op.drop_column('cambio')
        batch_op.drop_column('motor')
        batch_op.drop_column('ano')
        batch_op.drop_column('km')

    # ### end Alembic commands ###
