"""Descrição da migração

Revision ID: febfe9e7e7aa
Revises: a6231ed3a210
Create Date: 2023-11-11 12:15:36.261589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febfe9e7e7aa'
down_revision = 'a6231ed3a210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carros', schema=None) as batch_op:
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
